# Generated by Django 2.2 on 2020-10-25 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=30)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('thumbnail_link', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_threads', to='webapp.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_parent', models.BooleanField()),
                ('date_posted', models.DateTimeField()),
                ('content', models.TextField()),
                ('avatar_url', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=100)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thread_comments', to='webapp.Thread')),
            ],
        ),
    ]
