# Generated by Django 2.2 on 2020-11-06 02:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=30)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('thumbnail_link', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_threads', to='webapp.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('episode_number', models.IntegerField()),
                ('is_sad', models.BooleanField(default=False)),
                ('screenshot_url', models.TextField(blank=True, null=True)),
                ('synopsis', models.TextField()),
                ('characters', models.ManyToManyField(blank=True, to='webapp.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_parent', models.BooleanField()),
                ('date_posted', models.DateTimeField()),
                ('content', models.TextField()),
                ('avatar_url', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=100)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thread_comments', to='webapp.Thread')),
            ],
        ),
    ]
