# Generated by Django 2.2 on 2020-11-06 03:34

from django.db import migrations
from webapp.models.character import Character


def insert_characters(apps, schema_editor):
    Character.objects.create(name='Stan',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604023739/south%20park%20blog/characters/stan_iul4jc.png')
    Character.objects.create(name='Kyle',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604023738/south%20park%20blog/characters/kyle_gzbfux.png')
    Character.objects.create(name='Cartman',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604023739/south%20park%20blog/characters/cartman_wwegwt.png')
    Character.objects.create(name='Kenny',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604023739/south%20park%20blog/characters/kenny_s87fic.png')
    Character.objects.create(name='Butters',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604209310/south%20park%20blog/characters/butters_kyrnab.png')
    Character.objects.create(name='Wendy',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604209310/south%20park%20blog/characters/wendy_uqgwvg.png')
    Character.objects.create(name='Craig',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604209309/south%20park%20blog/characters/craig_ptgm8e.png')
    Character.objects.create(name='Tweek',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604209310/south%20park%20blog/characters/tweek_z9cy3h.png')
    Character.objects.create(name='Token',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604209309/south%20park%20blog/characters/token_xrc42t.png')
    Character.objects.create(name='Clyde',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604209309/south%20park%20blog/characters/clyde_dzgimx.png')
    Character.objects.create(name='Jimmy',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604209309/south%20park%20blog/characters/jimmy_ebk19v.png')
    Character.objects.create(name='Timmy',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604209309/south%20park%20blog/characters/timmy_qjacwi.png')
    Character.objects.create(name='Bebe',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604209308/south%20park%20blog/characters/bebe_ijd5bn.png')
    Character.objects.create(name='Heidi',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604209308/south%20park%20blog/characters/heidi_u1b0cg.png')
    Character.objects.create(name='Randy',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604209308/south%20park%20blog/characters/randy_eda77u.png')
    Character.objects.create(name='Mr. Garrison',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604209308/south%20park%20blog/characters/garrison_i6awon.png')
    Character.objects.create(name='Mr. Mackey',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604209308/south%20park%20blog/characters/mackey_mhcfmv.png')
    Character.objects.create(name='Chef',avatar_url='https://res.cloudinary.com/jmjcortez/image/upload/v1604209308/south%20park%20blog/characters/chef_lynsjc.png')

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_characters),
    ]
