# Generated by Django 2.2 on 2020-10-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_add_character_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('episode_number', models.IntegerField()),
                ('is_sad', models.BooleanField(default=False)),
                ('screenshot_url', models.TextField(blank=True, null=True)),
                ('characters', models.ManyToManyField(to='webapp.Character')),
            ],
        ),
    ]
