# Generated by Django 2.2 on 2020-10-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_add_episode_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
