# Generated by Django 2.2 on 2020-10-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_add_new_character_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='synopsis',
            field=models.TextField(default='synopsis'),
            preserve_default=False,
        ),
    ]
