# Generated by Django 2.2 on 2020-11-02 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_modify_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
